import re
from typing import Optional

def extract_title(text: str) -> str:
    first = text.strip().splitlines()[0] if text.strip() else "Автоматически сгенерированный тест"
    first = re.sub(r"[\.#:]+", "", first).strip()
    return first or "Автоматически сгенерированный тест"

def generate_testcase(prompt: str, prefer_style: Optional[str] = "concise") -> str:
    title = extract_title(prompt)
    
    # Разная логика в зависимости от содержания промпта
    prompt_lower = prompt.lower()
    
    if "авторизац" in prompt_lower or "логин" in prompt_lower or "вход" in prompt_lower:
        return f"""Название: {title}
Предусловие: Пользователь не авторизован.
Шаги:
1) Открыть страницу авторизации
   ОР: Отображается форма входа
2) Ввести валидный email/телефон
   ОР: Поле заполняется
3) Ввести пароль
   ОР: Пароль скрыт символами
4) Нажать кнопку «Войти»
   ОР: Происходит редирект в личный кабинет"""

    elif "регистрац" in prompt_lower or "созда" in prompt_lower:
        return f"""Название: {title}
Предусловие: Пользователь не зарегистрирован в системе.
Шаги:
1) Открыть форму регистрации
   ОР: Отображаются поля для ввода данных
2) Заполнить обязательные поля (email, пароль)
   ОР: Поля валидируются
3) Принять условия соглашения
   ОР: Чекбокс активирован
4) Нажать «Зарегистрироваться»
   ОР: Приходит письмо для подтверждения"""

    elif "поиск" in prompt_lower:
        return f"""Название: {title}
Предусловие: Пользователь находится на главной странице.
Шаги:
1) Найти поле поиска
   ОР: Поле доступно для ввода
2) Ввести поисковый запрос
   ОР: Текст отображается в поле
3) Нажать кнопку «Найти» или Enter
   ОР: Отображаются результаты поиска
4) Проверить релевантность результатов
   ОР: Результаты соответствуют запросу"""

    elif "корзин" in prompt_lower or "покуп" in prompt_lower:
        return f"""Название: {title}
Предусловие: Пользователь авторизован, товары в каталоге.
Шаги:
1) Выбрать товар в каталоге
   ОР: Карточка товара отображается
2) Нажать «Добавить в корзину»
   ОР: Счетчик корзины увеличивается
3) Перейти в корзину
   ОР: Отображается добавленный товар
4) Нажать «Оформить заказ»
   ОР: Открывается форма оформления"""

    elif "профиль" in prompt_lower or "личн" in prompt_lower:
        return f"""Название: {title}
Предусловие: Пользователь авторизован в системе.
Шаги:
1) Перейти в личный кабинет
   ОР: Отображается информация профиля
2) Нажать «Редактировать профиль»
   ОР: Открывается форма редактирования
3) Изменить данные (имя, телефон)
   ОР: Поля заполняются новыми значениями
4) Сохранить изменения
   ОР: Появляется сообщение об успешном сохранении"""

    else:
        # Универсальный шаблон для неизвестных сценариев
        return f"""Название: {title}
Предусловие: Система находится в рабочем состоянии.
Шаги:
1) Выполнить начальное действие
   ОР: Система реагирует корректно
2) Проверить основные функции
   ОР: Функциональность работает как ожидается
3) Завершить сценарий
   ОР: Результат соответствует требованиям"""

def generate_playwright(testcase_text: str, base_url: str = "http://localhost:3000") -> str:
    title = extract_title(testcase_text)
    prompt_lower = testcase_text.lower()
    
    # Разные playwright-скрипты в зависимости от типа теста
    if "авторизац" in prompt_lower or "логин" in prompt_lower:
        return f'''// Generated by AQA MVP - Authorization test
import {{ test, expect }} from '@playwright/test';

test.describe('Authorization', () => {{
  test('{title}', async ({{ page }}) => {{
    await page.goto('{base_url}/login');
    
    // Проверка страницы логина
    await expect(page.locator('h1')).toContainText(['Вход', 'Login', 'Sign in']);
    
    // Заполнение credentials
    await page.fill('input[type="email"]', 'test@example.com');
    await page.fill('input[type="password"]', 'password123');
    
    // Клик по кнопке входа
    await page.click('button[type="submit"]');
    
    // Проверка успешного входа
    await expect(page).toHaveURL(/{base_url.replace('//', '\/\/')}\/dashboard/);
    await expect(page.locator('.user-profile')).toBeVisible();
  }});
}});
'''

    elif "регистрац" in prompt_lower:
        return f'''// Generated by AQA MVP - Registration test  
import {{ test, expect }} from '@playwright/test';

test.describe('Registration', () => {{
  test('{title}', async ({{ page }}) => {{
    await page.goto('{base_url}/register');
    
    // Заполнение формы регистрации
    await page.fill('input[name="email"]', `test${{Date.now()}}@example.com`);
    await page.fill('input[name="password"]', 'securePassword123');
    await page.fill('input[name="confirmPassword"]', 'securePassword123');
    
    // Соглашение с условиями
    await page.check('input[type="checkbox"]');
    
    // Отправка формы
    await page.click('button[type="submit"]');
    
    // Проверка успешной регистрации
    await expect(page).toHaveURL(/{base_url.replace('//', '\/\/')}\/success/);
    await expect(page.locator('.confirmation-message')).toBeVisible();
  }});
}});
'''

    elif "поиск" in prompt_lower:
        return f'''// Generated by AQA MVP - Search test
import {{ test, expect }} from '@playwright/test';

test.describe('Search functionality', () => {{
  test('{title}', async ({{ page }}) => {{
    await page.goto('{base_url}');
    
    // Поиск товара
    await page.fill('input[type="search"]', 'test product');
    await page.press('input[type="search"]', 'Enter');
    
    // Проверка результатов
    await expect(page.locator('.search-results')).toBeVisible();
    await expect(page.locator('.product-item').first()).toBeVisible();
    
    // Проверка количества результатов
    const resultsCount = await page.locator('.product-item').count();
    expect(resultsCount).toBeGreaterThan(0);
  }});
}});
'''

    elif "корзин" in prompt_lower:
        return f'''// Generated by AQA MVP - Cart test
import {{ test, expect }} from '@playwright/test';

test.describe('Shopping cart', () => {{
  test('{title}', async ({{ page }}) => {{
    await page.goto('{base_url}/products');
    
    // Добавление товара в корзину
    await page.click('.product:first-child .add-to-cart');
    
    // Проверка счетчика корзины
    await expect(page.locator('.cart-counter')).toHaveText('1');
    
    // Переход в корзину
    await page.click('.cart-icon');
    
    // Проверка содержимого корзины
    await expect(page.locator('.cart-item')).toBeVisible();
    await expect(page.locator('.total-price')).toBeVisible();
  }});
}});
'''

    else:
        # Универсальный шаблон
        return f'''// Generated by AQA MVP - Generic test
import {{ test, expect }} from '@playwright/test';

test.describe('AQA Generated Test', () => {{
  test('{title}', async ({{ page }}) => {{
    await page.goto('{base_url}');
    
    // Базовые проверки
    await expect(page).toHaveURL(/{base_url.replace('//', '\/\/')}/);
    await expect(page.locator('body')).toBeVisible();
    
    // Пример взаимодействия с элементами
    const mainButton = page.locator('button.primary').first();
    if (await mainButton.isVisible()) {{
      await mainButton.click();
      // Добавь специфичные проверки по необходимости
    }}
    
    console.log('Test completed for: {title}');
  }});
}});
'''
