
import re
from typing import Optional

HEADER = """Название: {title}
Предусловие: Пользователь не авторизован.
Шаги:
1) Открыть {surface}
   ОР: Страница отображена
2) Нажать кнопку «Получить код»
   ОР: Кнопка задизейблена без валидного ввода
3) Ввести номер телефона (10 цифр)
   ОР: Кнопка становится активной
4) Нажать «Получить код»
   ОР: Появляется поле ввода SMS-кода
"""

def extract_title(text: str) -> str:
    # Простая эвристика: первая строка без пунктуации как заголовок
    first = text.strip().splitlines()[0]
    first = re.sub(r"[\.#:]+", "", first).strip()
    return first or "Автоматически сгенерированный тест"

def guess_surface(text: str) -> str:
    return "приложение/страницу авторизации" if "авториза" in text.lower() else "приложение"

def generate_testcase(prompt: str, prefer_style: Optional[str] = "concise") -> str:
    title = extract_title(prompt)
    surface = guess_surface(prompt)
    body = HEADER.format(title=title, surface=surface)
    # Небольшая нормализация: единый стиль действия «Нажать кнопку …»
    body = re.sub(r"(?i)(кликнуть|тапнуть|нажать на)", "Нажать", body)
    return body

def generate_playwright(testcase_text: str, base_url: str = "http://localhost:3000") -> str:
    # Простая конвертация шагов в шаблон Playwright
    return f'''// Generated by AQA MVP
import {{ test, expect }} from '@playwright/test';

test.describe('AQA Generated', () => {{
  test('{extract_title(testcase_text)}', async ({{ page }}) => {{
    await page.goto(process.env.APP_URL || '{base_url}');
    // Шаг 1: проверка страницы
    await expect(page).toHaveURL(/.+/);

    // Шаг 2: кнопка «Получить код» disabled до валидного ввода
    const getCodeBtn = page.locator('button#get-code');
    await expect(getCodeBtn).toBeDisabled();

    // Шаг 3: ввод телефона
    const phone = page.locator('input[name="phone"]');
    await phone.fill('7999888776'); // 10 цифр (пример)
    await expect(getCodeBtn).toBeEnabled();

    // Шаг 4: переход на ввод SMS
    await getCodeBtn.click();
    await expect(page.locator('input[name="smsCode"]')).toBeVisible();
  }});
}});
'''
